feat: Use of flags and invalid format detection

diff --git a/khicad b/khicad
--- a/khicad
+++ b/khicad
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-# Ctrl + L
-tput -x clear
 # Import dotenv
 set -a; source "$(dirname "$0")/".env; set +a
 
@@ -15,40 +13,34 @@ hide_cursor(){
 	tput civis
 }
 
-# Promp the user to get all necessary values for the script
-printf "$(tput bold)Enter album url: $(tput sgr0)"
-read albumurl
-# Extract urls of the songs in the album
-urls=$(curl -s "$albumurl" | grep -oiE "/game-soundtracks/album/.*.mp3" | uniq)
-status=$?
-if [ "${urls[0]}" == "" ]; then
-	echo "$(tput bold)$(tput setaf 1)Invalid url$(tput sgr0)"
+# Read supplied arguments
+while getopts u:n:f: option; do
+   case $option in
+    u)
+      albumurl=${OPTARG};;
+    n)
+      albumname=${OPTARG};;
+    f)
+      format=${OPTARG};;
+    ?)
+      echo "script usage: khicad [-u album_url] [-n album_name] [-f file_format]" >&2
+      exit 1
+      ;;
+  esac
+done
+
+if [ -z "${albumurl+x}" ] || [ -z "${albumname+x}" ] || [ -z "${format+x}" ]; then
+      echo "script usage: khicad [-u album_url] [-n album_name] [-f file_format]" >&2
+      exit 1
 fi
 
-printf "$(tput bold)Enter album name: $(tput sgr0)"
-read albumname
-
-# Get total size and ask for song format
-infosizemp3=$(curl -s "$albumurl" | grep -o "Total.Filesize:.*</b>" | cut -d\> -f2 | cut -d\< -f1 )
-infosizeflac=$(curl -s "$albumurl" | grep -o "Total.Filesize:.*</b>" | cut -d\> -f4 | cut -d\< -f1 )
-PS3="$(tput bold)Choose file format: $(tput sgr0)"
-options=("$(tput setaf 4)mp3 ($infosizemp3)$(tput sgr0)" "$(tput setaf 4)flac ($infosizeflac)$(tput sgr0)")
-select opt in "${options[@]}"
-
-do
-	case $opt in
-		"${options[0]}")
-			format="mp3"
-			;;
-		"${options[1]}")
-			format="flac"
-			;;
-		*) 
-			echo "$(tput bold)$(tput setaf 3)Invalid Option, defaulting to mp3$(tput sgr0)"
-			format="mp3";;
-	esac
-	break
-done
+# Extract urls of the songs in the album
+urls=$(curl -s "$albumurl" | grep -oiE "/game-soundtracks/album/.*.mp3" | uniq | xargs -I{} echo "https://downloads.khinsider.com{}")
+status=$?
+if [ "${urls[0]}" == "" ]; then
+	echo "$(tput bold)$(tput setaf 1)Invalid url$(tput sgr0)" >&2
+	exit 1
+fi
 
 # Hide cursor and set up TERM catch
 trap show_cursor INT TERM
@@ -63,21 +55,20 @@ counter=0
 totalsongs=$(echo "$urls" | wc -l)
 for url in $urls;
 do
-	counter=$((counter+1))
-	
-	if test 10 -gt $counter
-	then
-		songnumber="0$counter"
-	else
-		songnumber=$counter
+	songlink=$(curl -s "$url" | grep -o "https://vgmsite.com/soundtracks/.*.$format" | uniq)
+
+	if [ "${songlink}" == "" ]; then
+		echo "$(tput bold)$(tput setaf 1)Invalid file format$(tput sgr0)" >&2
+		show_cursor
 	fi
 	
-	songname="$songnumber $(curl -s "https://downloads.khinsider.com$url" | grep -o "Song.name:.<b>.*</b>" | cut -d\< -f2 | cut -d\> -f2).$format"
+	counter=$((counter+1))
+	songnumber=$(printf "%0"${#totalsongs}"d" $counter)
 	
+	songname="$songnumber $(curl -s "$url" | grep -o "Song.name:.<b>.*</b>" | cut -d\< -f2 | cut -d\> -f2).$format"
 	progress="$counter/$totalsongs"
 	echo -ne "$(tput setaf 2)$(tput bold)$progress$(tput sgr0) | $(tput setaf 2)Downloading song: $songname$(tput sgr0)\033[0K\r"
 
-	songlink=$(curl -s "https://downloads.khinsider.com$url" | grep -o "https://vgmsite.com/soundtracks/.*.$format" | uniq)
 	curl "$songlink" --output-dir "$albumdir" --output "$songname" --silent
 done
 
